default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: <%= ENV['CYPRESS'] ? 'my_db_test' : 'ProdTalkAI_development' %>

test:
  <<: *default
  database: ProdTalkAI_test

production:
  <<: *default
  database: ProdTalkAI_production
  username: ProdTalkAI
  password: <%= ENV['PRODTALKAI_DATABASE_PASSWORD'] %>
